In [9]:
from typing import Tuple
import numpy as np

In [10]:
def get_dataset() -> Tuple[np.ndarray, np.ndarray]:
    x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    y = np.array([[0], [1], [1], [1]])
    return x, y

In [11]:
def to_categorical(y: np.ndarray, num_classes: int) -> np.ndarray:
    y_categorical = np.zeros(shape=(len(y), num_classes))
    for i, yi in enumerate(y):
        y_categorical[i, yi] = 1
    return y_categorical

In [12]:
def softmax(y_pred: np.ndarray) -> np.ndarray:
    probabilities = np.zeros_like(y_pred)
    for i in range(len(y_pred)):
        exps = np.exp(y_pred[i])
        probabilities[i] = exps / np.sum(exps)
    return probabilities

In [13]:
def cross_entropy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    num_samples = y_true.shape[0]
    loss = -np.sum(y_true * np.log(y_pred) / num_samples)
    return loss

In [18]:
if __name__=='__main__':
    x, y = get_dataset()
    y_true = to_categorical(y, num_classes = 2)
    print(y)
    print(y_categorical)
    
    y_logits = np.array([[10.8, -3.3], [12.2, 21.8], [1.1, 4.9], [1.05, 3.95]])

    y_pred = softmax(y_logits)
    print(y_pred)

    loss = cross_entropy(y_true, y_pred)
    print(loss)

[[0]
 [1]
 [1]
 [1]]
[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[9.99999248e-01 7.52397733e-07]
 [6.77241496e-05 9.99932276e-01]
 [2.18812709e-02 9.78118729e-01]
 [5.21535631e-02 9.47846437e-01]]
0.01893886787846552
